// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CropScreenshots(arg1, arg2, arg3) {
  return window['go']['main']['App']['CropScreenshots'](arg1, arg2, arg3);
}

export function GetDefaultOutputDir() {
  return window['go']['main']['App']['GetDefaultOutputDir']();
}

export function LoadScreenshots(arg1) {
  return window['go']['main']['App']['LoadScreenshots'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickOutputFolder() {
  return window['go']['main']['App']['PickOutputFolder']();
}
