// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cropper} from '../models';
import {scanner} from '../models';

export function CropScreenshots(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<cropper.Result>>;

export function GetDefaultOutputDir():Promise<string>;

export function LoadScreenshots(arg1:Array<string>):Promise<Array<scanner.Screenshot>>;

export function PickFolder():Promise<string>;

export function PickOutputFolder():Promise<string>;
